### ISSUE TITLE
Collapsed filters will overflow into report

### ISSUE THREAD

**Issue by kevinhinterlong** [yahoo/navi#638]
**Describe the bug**
The collapsed filters will overflow into the body of the report

**To Reproduce**
Make a report, add a bunch of filter values

**Expected behavior**
The collapsed filters have a max length and will force text to cut off when needed

**Screenshots**
![Report with many filter values](https://user-images.githubusercontent.com/12093492/73297143-a5ddc900-41d0-11ea-92eb-d9b89c7ecb80.png)

**Solution**
```css
.filter-collection--collapsed-item { 
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    display: inline-block;
    max-width: 100%;
}
```
